name = "Plumber"
uuid = "49a8456a-4ba5-11e9-3740-3f4f22e0c893"
authors = ["onetonfoot <onetonfoot@gmail.com>"]
version = "0.0.1"

[deps]
ExprManipulation = "49bccec5-5f8e-4a37-813c-bb803a7e462a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia ="^1"
ExprManipulation = "^0.1"